# permissions for end users to edit federatedlearnings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: editor-role
rules:
- apiGroups:
  - federation-ai.open-cluster-management.io
  resources:
  - federatedlearnings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - federation-ai.open-cluster-management.io
  resources:
  - federatedlearnings/status
  verbs:
  - get
