---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersetbindings
  - managedclustersets
  - managedclustersets/bind
  - managedclustersets/finalizers
  - managedclustersets/join
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placementdecisions
  - placements
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - federation-ai.open-cluster-management.io
  resources:
  - federatedlearnings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - federation-ai.open-cluster-management.io
  resources:
  - federatedlearnings/finalizers
  verbs:
  - update
- apiGroups:
  - federation-ai.open-cluster-management.io
  resources:
  - federatedlearnings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - placementbindings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
